### ISSUE TITLE
mining block crashes game?

### ISSUE THREAD

**Issue by huu-bo** [huu-bo/micg#4]
Traceback (most recent call last):
  File "main.py", line 188, in <module>
    world.set(math.floor(mouse_pos[0] / size + px), math.floor(mouse_pos[1] / size + py) - 20, b)
  File "/home/huub/PycharmProjects/micg/noise.py", line 186, in set
    self.world[x // 40][y][x % 40] = value
KeyError: 0

while mining bedrock

**Comment by huu-bo** [comment]
oops
